DROP TABLE IF EXISTS TRACKED_OBJECTS;
DROP TABLE IF EXISTS FILES;
DROP TABLE IF EXISTS CLASSIFICATIONS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS HIGHRESIMAGES; 
DROP TABLE IF EXISTS CLASSIFIER_SAMPLES;
DROP TABLE IF EXISTS CAMERA_SESSION;
DROP TABLE IF EXISTS CAMERAS;


CREATE TABLE TRACKED_OBJECTS(	ID INTEGER,
								PATH TEXT,
								FRAME_START INTEGER NOT NULL,
								FRAME_END INTEGER NOT NULL,
								XYWH_TRACK TEXT,
								PRIMARY KEY(ID, PATH),
								FOREIGN KEY(PATH) REFERENCES FILES(PATH)
								); 

CREATE TABLE FILES(	PATH TEXT PRIMARY KEY,
					MOTION_RAN INTEGER,
					FRAME_COUNT INTEGER,
					W INTEGER,
					H INTEGER,
					RESIZED_W INTEGER,
					RESIZED_H INTEGER,
					END_TIME INTEGER
					);

CREATE TABLE CAMERA_SESSION(CAMERA_NAME TEXT,
					PATH TEXT,
					FRAMESPERFILE TEXT,
					FRAME_COUNT TEXT,
					START_TIME TEXT,
					ISRUNNING TEXT,
					PRIMARY KEY(CAMERA_NAME, START_TIME)
					);

CREATE TABLE CAMERAS(NAME PRIMARY KEY,
					MODEL TEXT,
					MAX_RESOLUTION TEXT,
					RTSP_URL TEXT
					);

CREATE TABLE CLASSIFICATIONS(
	NAME	TEXT,
	CLASSIFIER	BLOB,
	LAST_RUN	INTEGER,
	NUM_SAMPLES	INTEGER,
	SAMPLE_DEPTH	INTEGER,
	PRIMARY KEY(NAME)
);

CREATE TABLE HIGHRESIMAGES (PATH TEXT,
							FRAME_INDEX INTEGER,
							IMAGE_FILENAME TEXT
							);

CREATE TABLE CLASSIFIER_SAMPLES (	PATH TEXT,
									FRAME_INDEX INTEGER,
									X INTEGER,
									Y INTEGER,
									W INTEGER,
									H INTEGER,
									CLASSIFICATION_NAME TEXT,
									IMAGE BLOB,
									LAST_RUN INTEGER,
									PRIMARY KEY(PATH,FRAME_INDEX,X,Y,CLASSIFICATION_NAME)
								);
INSERT INTO CAMERAS (NAME, MODEL, MAX_RESOLUTION, RTSP_URL) VALUES ("Note9", "Android", "4K", "rtsp://larry:garbledun@192.168.219.4:5540/ch0");
INSERT INTO CAMERAS (NAME, MODEL, MAX_RESOLUTION, RTSP_URL) VALUES ("LG", "Android", "4K", "rtsp://larry:garbledun@192.168.219.11:5540/ch0");
INSERT INTO CAMERAS (NAME, MODEL, MAX_RESOLUTION, RTSP_URL) VALUES ("CLEARVIEW 4k", "REOLINK", "4K", "rtsp://larry:garbledun@192.168.219.2:554/h265Preview_01_main");
INSERT INTO CAMERAS (NAME, MODEL, MAX_RESOLUTION, RTSP_URL) VALUES ("REOLink - LinkSys", "REOLINK", "VGA", "rtsp://larry:garbledun@192.168.1.123:554/h264Preview_01_sub");
INSERT INTO CAMERAS (NAME, MODEL, MAX_RESOLUTION, RTSP_URL) VALUES ("FLUENT 640x480", "REOLINK", "VGA", "rtsp://larry:garbledun@192.168.219.2:554/h264Preview_01_sub");